### PR TITLE
lots of changes

### PR DESCRIPTION
**Pull request by soumith**
to summarize:
- a ton of bug fixes
- latest tty.js / term.js
- added a command-line tool called "gfx" which can quickly clear the cache, or show images from shell.

``` bash
$ gfx                                                                                                                                                                                                                               
Usage: gfx [options] image-filename1 [image-filename2] [image-filename3]                                                                                                                                                                   
Options:                                                                                                                                                                                                                                   
  -collage : instead of displaying the list of images in separate windows, loads them as a collage in the same window                                                                                                                      
  -clearcache : clears all the cached dom elements in ~/.gfx.js/static/data                                                                                                                                                                

Example:                                                                                                                                                                                                                                   
gfx a.jpg                                                                                                                                                                                                                                  

gfx *.jpg     
```

### CODE REVIEW

**Comment by clementfarabet** [comment]
Hey Soumith, that looks great. Are all these features incremental / additive, or did you actually kill some of the existing functionalities?

**Comment by clementfarabet** [comment]
Btw cool idea to have a standalone exec.

**Comment by soumith** [comment]
i did not kill any existing functionality, everything that was working will work the same.

**Comment by clementfarabet** [comment]
Cool, merging then.

**Comment by soumith** [comment]
the default URL will now be https:// thats the only change that kills the existing functionality.

**Comment by soumith** [comment]
but i included a default certificate to accompany the distribution.

**Comment by clementfarabet** [comment]
I just installed it, but it seems to still be running on http, not https.
Normal?

On Wed, May 14, 2014 at 11:53 AM, Soumith Chintala <notifications@github.com

**Comment by clementfarabet** [comment]
OK just got it, I had to restart it. The SSL certificate can't be trusted
though, it gives me a big warning in chrome, do you get that too?

On Wed, May 14, 2014 at 11:57 AM, Clément Farabet <clement.farabet@gmail.com

> wrote:
> 
> I just installed it, but it seems to still be running on http, not https.
> Normal?
> 
> On Wed, May 14, 2014 at 11:53 AM, Soumith Chintala <

**Comment by soumith** [comment]
yea, that's a side-effect of a self-signed cert. 

I'll try get a certificate for localhost from one of the Certificate Authorities, never did it for localhost, so lets see how this works.

**Comment by clementfarabet** [comment]
Cool. Also since the certificate is availabel publicly in the git repo, I
wonder how secure it actually is :-).

On Wed, May 14, 2014 at 12:03 PM, Soumith Chintala <notifications@github.com

**Comment by soumith** [comment]
yea, it isn't secure against MITM attacks :) but no one can snoop over the network with some command-line client and see all your plots and images, they have to sit between you and the server (serving gfx.js) and they have to do that at the time of key-exchange.

i'd say it's better than nothing but worse than perfect :D

**Comment by clementfarabet** [comment]
yeah cool!

On Wed, May 14, 2014 at 12:07 PM, Soumith Chintala <notifications@github.com

**Pull request merged**
