### PR TITLE
reliable file watching using chokidar

### PR DESCRIPTION
**Pull request by soumith**
i keep a copy of chokidar in lib/ as i removed the check in #226.
the chokidar guys have an issue open with that bug, i think they dont want a mergeback because of "performance reasons"

### CODE REVIEW

**Comment by soumith** [comment]
*#236

**Comment by clementfarabet** [comment]
Hey Soumith, so can you confirm thta this patch preserves the same behavior (i.e. no issue with first graphics rendered, ...).

**Comment by soumith** [comment]
yes, it preserves existing behavior, fixes the chokidar bug that results in the first graphics not showing up.

**Comment by clementfarabet** [comment]
awesome, thanks a lot for that

**Pull request merged**
